version: '3'

services:

  web:
    image: nginx:1.15
    volumes:
      - .:/app
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
#      RAILS_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    depends_on:
      - db

  db:
    image: postgres:11.2
    volumes:
      - ../dumps:/dumps
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pg_data: