version: '3'

services:

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:11.2
    volumes:
      - ../dumps:/dumps
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pg_data: